// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@yh-firewall.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "get": {
                "description": "获取当前防火墙配置",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取配置",
                "responses": {
                    "200": {
                        "description": "配置内容",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "错误信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "更新防火墙配置",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "config"
                ],
                "summary": "更新配置",
                "parameters": [
                    {
                        "description": "JSON 格式的配置内容",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "错误信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/connection": {
            "get": {
                "description": "获取当前所有活跃的网络连接",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "获取连接列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/YH-FireWall_internal_model_conn.Info"
                            }
                        }
                    }
                }
            }
        },
        "/connection/{id}": {
            "delete": {
                "description": "强制关闭指定 ID 的网络连接",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "关闭连接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "错误信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/interface": {
            "get": {
                "description": "获取当前系统所有网络接口信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "获取网卡列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/YH-FireWall_internal_model_itf.Itf"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "健康检查",
                "tags": [
                    "system"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/protocol": {
            "get": {
                "description": "获取防火墙支持的所有 IP 协议名称",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "获取协议列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rule": {
            "get": {
                "description": "返回防火墙规则列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rule"
                ],
                "summary": "获取所有规则",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/YH-FireWall_internal_model_rule.Data"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "添加一条防火墙规则",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "rule"
                ],
                "summary": "添加规则",
                "parameters": [
                    {
                        "description": "规则配置",
                        "name": "option",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/YH-FireWall_internal_model_rule.Option"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "规则ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rule/{id}": {
            "put": {
                "description": "更新指定 ID 的防火墙规则",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "rule"
                ],
                "summary": "更新规则",
                "parameters": [
                    {
                        "type": "string",
                        "description": "规则ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "规则配置",
                        "name": "option",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/YH-FireWall_internal_model_rule.Option"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定 ID 的防火墙规则",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "rule"
                ],
                "summary": "删除规则",
                "parameters": [
                    {
                        "type": "string",
                        "description": "规则ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "YH-FireWall_internal_model_conn.Info": {
            "type": "object",
            "properties": {
                "direction": {
                    "description": "网卡方向信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/YH-FireWall_internal_model_flow.Direction"
                        }
                    ]
                },
                "establishTime": {
                    "description": "建立时间",
                    "type": "integer"
                },
                "id": {
                    "description": "连接id",
                    "type": "string"
                },
                "localIP": {
                    "$ref": "#/definitions/netip.AddrPort"
                },
                "process": {
                    "description": "进程信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/YH-FireWall_internal_model_proc.Info"
                        }
                    ]
                },
                "protocol": {
                    "description": "连接信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/layers.IPProtocol"
                        }
                    ]
                },
                "remoteIP": {
                    "$ref": "#/definitions/netip.AddrPort"
                }
            }
        },
        "YH-FireWall_internal_model_flow.Direction": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "Inbound",
                "Outbound",
                "Forward",
                "Unknown"
            ]
        },
        "YH-FireWall_internal_model_itf.Itf": {
            "type": "object",
            "properties": {
                "addrs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "flags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "mac": {
                    "type": "string"
                },
                "mtu": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "YH-FireWall_internal_model_proc.Info": {
            "type": "object",
            "properties": {
                "cmdline": {
                    "type": "string"
                },
                "exe": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "YH-FireWall_internal_model_rule.Data": {
            "type": "object",
            "properties": {
                "accept": {
                    "type": "boolean"
                },
                "comment": {
                    "type": "string"
                },
                "dstNets": {
                    "type": "string"
                },
                "dstPorts": {
                    "type": "string"
                },
                "enable": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inDevs": {
                    "type": "string"
                },
                "outDevs": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "protocols": {
                    "type": "string"
                },
                "srcNets": {
                    "type": "string"
                },
                "srcPorts": {
                    "type": "string"
                }
            }
        },
        "YH-FireWall_internal_model_rule.Option": {
            "type": "object",
            "properties": {
                "accept": {
                    "type": "boolean"
                },
                "comment": {
                    "type": "string"
                },
                "dstNets": {
                    "type": "string"
                },
                "dstPorts": {
                    "type": "string"
                },
                "enable": {
                    "type": "boolean"
                },
                "group": {
                    "type": "string"
                },
                "inDevs": {
                    "type": "string"
                },
                "outDevs": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "protocols": {
                    "type": "string"
                },
                "srcNets": {
                    "type": "string"
                },
                "srcPorts": {
                    "type": "string"
                }
            }
        },
        "layers.IPProtocol": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                4,
                6,
                17,
                27,
                41,
                43,
                44,
                47,
                50,
                51,
                58,
                59,
                60,
                89,
                94,
                97,
                112,
                132,
                136,
                137
            ],
            "x-enum-varnames": [
                "IPProtocolIPv6HopByHop",
                "IPProtocolICMPv4",
                "IPProtocolIGMP",
                "IPProtocolIPv4",
                "IPProtocolTCP",
                "IPProtocolUDP",
                "IPProtocolRUDP",
                "IPProtocolIPv6",
                "IPProtocolIPv6Routing",
                "IPProtocolIPv6Fragment",
                "IPProtocolGRE",
                "IPProtocolESP",
                "IPProtocolAH",
                "IPProtocolICMPv6",
                "IPProtocolNoNextHeader",
                "IPProtocolIPv6Destination",
                "IPProtocolOSPF",
                "IPProtocolIPIP",
                "IPProtocolEtherIP",
                "IPProtocolVRRP",
                "IPProtocolSCTP",
                "IPProtocolUDPLite",
                "IPProtocolMPLSInIP"
            ]
        },
        "netip.AddrPort": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "YH FireWall API",
	Description:      "YH FireWall 防火墙管理接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
